### ISSUE TITLE
No module named periodictable

### ISSUE THREAD

**Issue by WillDeSnoo** [share1992/PathReducer#2]
When trying to use the example scripts, I get an error from importing the periodictable module:

from periodictable import *
ModuleNotFoundError: No module named 'periodictable'

I have installed the requirements as the README suggests :

pip install -r requirements.txt

Do I need to import the periodictable package separately?

**Comment by share1992** [comment]
The periodictable package is included in the requirements.txt file, so it should have been installed when you ran `pip install`.

Are you sure all packages successfully installed?

Are you running PathReducer in the same environment you installed the required packages?

**Comment by WillDeSnoo** [comment]
Thanks for the feedback! As you said I was running it in a different environment, thanks for your help!

**Comment by share1992** [comment]
Awesome, no problem at all (also, a mistake I make all the time)! :)
